In [58]:
import pandas as pd
from pandas_profiling import ProfileReport

# Importación de datos

In [59]:
df = pd.read_csv("data/dataset_SCL.csv")

In [60]:
profile_name = "Fligths data report"
profile = ProfileReport(df, title=profile_name )
profile.to_file(output_file='{}.html'.format(profile_name ))

Summarize dataset: 100%|██████████| 36/36 [00:10<00:00,  3.48it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.83s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.50it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 198.76it/s]

In [61]:
df.head()

,Fecha-I,Vlo-I,Ori-I,Des-I,Emp-I,Fecha-O,Vlo-O,Ori-O,Des-O,Emp-O,DIA,MES,AÑO,DIANOM,TIPOVUELO,OPERA,SIGLAORI,SIGLADES
0,2017-01-01 23:30:00,226,SCEL,KMIA,AAL,2017-01-01 23:33:00,226,SCEL,KMIA,AAL,1,1,2017,Domingo,I,American Airlines,Santiago,Miami
1,2017-01-02 23:30:00,226,SCEL,KMIA,AAL,2017-01-02 23:39:00,226,SCEL,KMIA,AAL,2,1,2017,Lunes,I,American Airlines,Santiago,Miami
2,2017-01-03 23:30:00,226,SCEL,KMIA,AAL,2017-01-03 23:39:00,226,SCEL,KMIA,AAL,3,1,2017,Martes,I,American Airlines,Santiago,Miami
3,2017-01-04 23:30:00,226,SCEL,KMIA,AAL,2017-01-04 23:33:00,226,SCEL,KMIA,AAL,4,1,2017,Miercoles,I,American Airlines,Santiago,Miami
4,2017-01-05 23:30:00,226,SCEL,KMIA,AAL,2017-01-05 23:28:00,226,SCEL,KMIA,AAL,5,1,2017,Jueves,I,American Airlines,Santiago,Miami

- Fecha-I : Fecha y hora programada del vuelo.
- Vlo-I : Número de vuelo programado.
- Ori-I : Código de ciudad de origen programado.
- Des-I : Código de ciudad de destino programado.
- Emp-I : Código aerolínea de vuelo programado.
- Fecha-O : Fecha y hora de operación del vuelo.
- Vlo-O : Número de vuelo de operación del vuelo.
- Ori-O : Código de ciudad de origen de operación
- Des-O : Código de ciudad de destino de operación.
- Emp-O : Código aerolínea de vuelo operado.
- DIA : Día del mes de operación del vuelo.
- MES : Número de mes de operación del vuelo.
- AÑO : Año de operación del vuelo.
- DIANOM : Día de la semana de operación del vuelo.
- TIPOVUELO : Tipo de vuelo, I =Internacional, N =Nacional.
- OPERA : Nombre de aerolínea que opera.
- SIGLAORI : Nombre ciudad origen.
- SIGLADES : Nombre ciudad destino.

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68206 entries, 0 to 68205
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Fecha-I    68206 non-null  object
 1   Vlo-I      68206 non-null  object
 2   Ori-I      68206 non-null  object
 3   Des-I      68206 non-null  object
 4   Emp-I      68206 non-null  object
 5   Fecha-O    68206 non-null  object
 6   Vlo-O      68205 non-null  object
 7   Ori-O      68206 non-null  object
 8   Des-O      68206 non-null  object
 9   Emp-O      68206 non-null  object
 10  DIA        68206 non-null  int64
 11  MES        68206 non-null  int64
 12  AÑO        68206 non-null  int64
 13  DIANOM     68206 non-null  object
 14  TIPOVUELO  68206 non-null  object
 15  OPERA      68206 non-null  object
 16  SIGLAORI   68206 non-null  object
 17  SIGLADES   68206 non-null  object
dtypes: int64(3), object(15)
memory usage: 9.4+ MB

# APUNTES

- En el reporte generado se encontró lo siguiente:
    - Las dos columnas de fecha no tienen el formarto correcto
    - Las columnas Vlo-I y Vlo-O tienen la etiqueta "not support" por lo que tienen problemas. Se revisará y corregirá
    - Las columnas Ori-O, Ori-I y SIGLAORI son columnas con valor constante.
        - Ori-O : "SCEL"
        - Ori-I : "SCEL"
        - SIGLAORI : "Santiago"

# LIMPIEZA

In [63]:
datetime_format = "%Y-%m-%d %H:%M:%S"
df["Fecha-I"] = pd.to_datetime(df["Fecha-I"], format=datetime_format)
df["Fecha-O"] = pd.to_datetime(df["Fecha-O"], format=datetime_format)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68206 entries, 0 to 68205
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Fecha-I    68206 non-null  datetime64[ns]
 1   Vlo-I      68206 non-null  object
 2   Ori-I      68206 non-null  object
 3   Des-I      68206 non-null  object
 4   Emp-I      68206 non-null  object
 5   Fecha-O    68206 non-null  datetime64[ns]
 6   Vlo-O      68205 non-null  object
 7   Ori-O      68206 non-null  object
 8   Des-O      68206 non-null  object
 9   Emp-O      68206 non-null  object
 10  DIA        68206 non-null  int64
 11  MES        68206 non-null  int64
 12  AÑO        68206 non-null  int64
 13  DIANOM     68206 non-null  object
 14  TIPOVUELO  68206 non-null  object
 15  OPERA      68206 non-null  object
 16  SIGLAORI   68206 non-null  object
 17  SIGLADES   68206 non-null  object
dtypes: datetime64[ns](2), int64(3), object(13)
memory usage: 9.4+ MB

In [10]:
len(list(df["Vlo-I"].unique()))

750

In [65]:
list(df["Vlo-I"].unique())

['226',
 '912',
 '940',
 '92',
 '93',
 '401',
 '11',
 '1011',
 '1281',
 '1283',
 '1285',
 '1287',
 '1289',
 '1291',
 '2291',
 '98',
 '116',
 '176',
 '240',
 '295',
 '689',
 '250',
 '112',
 '118',
 '174',
 '249',
 '276',
 '495',
 '4495',
 '146',
 '7661',
 '7663',
 '9245',
 '9268',
 '9362',
 '6830',
 '702',
 '624',
 '28',
 '846',
 '709',
 '741',
 '8021',
 '8023',
 '8027',
 '8029',
 '8069',
 '8073',
 '8075',
 '8099',
 '8125',
 '8137',
 '8160',
 '8161',
 '9601',
 '9615',
 '9651',
 '9653',
 '9661',
 '9689',
 '9782',
 '9623',
 '1',
 '3',
 '7',
 '9',
 '13',
 '15',
 '17',
 '21',
 '23',
 '25',
 '41',
 '43',
 '51',
 '53',
 '55',
 '61',
 '71',
 '73',
 '75',
 '81',
 '83',
 '102',
 '104',
 '106',
 '108',
 '110',
 '120',
 '122',
 '128',
 '130',
 '132',
 '134',
 '140',
 '142',
 '150',
 '156',
 '160',
 '162',
 '164',
 '166',
 '170',
 '172',
 '180',
 '182',
 '184',
 '186',
 '188',
 '190',
 '192',
 '194',
 '196',
 '501',
 '503',
 '507',
 '521',
 '531',
 '551',
 '800',
 '802',
 '804',
 '1083',
 '14',
 '31',
 '35',
 '37',
 '57',
 '65',
 '67',
 '69',
 '89',
 '91',
 '97',
 '114',
 '124',
 '126',
 '136',
 '138',
 '144',
 '148',
 '152',
 '154',
 '168',
 '178',
 '201',
 '203',
 '207',
 '209',
 '211',
 '213',
 '215',
 '217',
 '219',
 '221',
 '231',
 '233',
 '235',
 '237',
 '239',
 '241',
 '247',
 '251',
 '257',
 '259',
 '261',
 '263',
 '265',
 '267',
 '269',
 '271',
 '273',
 '275',
 '277',
 '279',
 '281',
 '283',
 '285',
 '287',
 '289',
 '291',
 '293',
 '297',
 '300',
 '302',
 '304',
 '306',
 '308',
 '312',
 '314',
 '318',
 '320',
 '322',
 '324',
 '326',
 '328',
 '330',
 '332',
 '334',
 '336',
 '338',
 '340',
 '342',
 '344',
 '346',
 '348',
 '350',
 '366',
 '374',
 '380',
 '382',
 '384',
 '386',
 '388',
 '396',
 '403',
 '405',
 '439',
 '443',
 '445',
 '449',
 '451',
 '455',
 '461',
 '481',
 '500',
 '502',
 '504',
 '510',
 '530',
 '532',
 '534',
 '546',
 '572',
 '574',
 '576',
 '582',
 '592',
 '600',
 '602',
 '622',
 '632',
 '642',
 '646',
 '648',
 '650',
 '704',
 '708',
 '750',
 '752',
 '760',
 '772',
 '776',
 '778',
 '798',
 '801',
 '833',
 '841',
 '843',
 '845',
 '849',
 '900',
 '902',
 '906',
 '910',
 '930',
 '932',
 '934',
 '942',
 '952',
 '954',
 '968',
 '970',
 '972',
 '986',
 '988',
 '991',
 '993',
 '1320',
 '1322',
 '1326',
 '1334',
 '1357',
 '1359',
 '1446',
 '1498',
 '2632',
 '2636',
 '2638',
 '2640',
 '2650',
 '2702',
 '4501',
 '4503',
 '1003',
 '1004',
 '1005',
 '1302',
 '1340',
 '200',
 '700',
 '1704',
 '33',
 '59',
 '95',
 '243',
 '634',
 '1200',
 '1202',
 '1300',
 '1071',
 '99',
 '158',
 '198',
 '205',
 '376',
 '378',
 '404',
 '406',
 '410',
 '414',
 '430',
 '432',
 '434',
 '438',
 '486',
 '492',
 '536',
 '638',
 '640',
 '644',
 '864',
 '890',
 '892',
 '1122',
 '1126',
 '1151',
 '1363',
 '1946',
 '2370',
 '2372',
 '2374',
 '7811',
 '7813',
 '1165',
 '1301',
 '1351',
 '1906',
 '204',
 '9625',
 '8665',
 '4950',
 '45',
 '100',
 '523',
 '1025',
 '4000',
 '63',
 '352',
 '354',
 '452',
 '460',
 '636',
 '674',
 '888',
 '895',
 '897',
 '1108',
 '1124',
 '1128',
 '1236',
 '1248',
 '2364',
 '2366',
 '2378',
 '2474',
 '2478',
 '1050',
 '1051',
 '1052',
 '1061',
 '1101',
 '1102',
 '1104',
 '1130',
 '1159',
 '1230',
 '202',
 '989P',
 '3000',
 '9000',
 '459',
 '483',
 '1114',
 '1168',
 '1238',
 '1239',
 '1261',
 '1107',
 '1140',
 '1167',
 '1271',
 '1031',
 '1700',
 '940P',
 '9659',
 '1551',
 '1800',
 '358',
 '1103',
 '1111',
 '2518',
 '7959',
 '400',
 '402',
 '2297',
 '9244',
 '9246',
 '9247',
 '9261',
 '9272',
 '9673',
 '9956',
 '9600',
 '9629',
 '9662',
 '9701',
 '9955',
 '5',
 '77',
 '553',
 '316',
 '368',
 '372',
 '470',
 '506',
 '604',
 '1136',
 '1158',
 '1242',
 '1244',
 '2368',
 '2486',
 '1105',
 '1106',
 '1113',
 '1115',
 '1132',
 '1155',
 '1166',
 '2488',
 '1400',
 '1033',
 '4',
 '8',
 '26',
 '22',
 '1927',
 '7721',
 '591P',
 '846A',
 '8519',
 '8525',
 '8541',
 '8542',
 '9622',
 '356',
 '1138',
 '1148',
 '1041',
 '6',
 '32',
 '50',
 '52',
 '86',
 '88',
 '9301',
 '9303',
 '47',
 '60',
 '1234',
 '1250',
 '1241',
 '1034',
 '1035',
 '1043',
 '7704',
 '10',
 '253',
 '1502',
 '8083',
 '8131',
 '9851',
 '27',
 '543',
 '1198',
 '39',
 '87',
 '390',
 '448',
 '664',
 '805',
 '1054',
 '1065',
 '1116',
 '1121',
 '1146',
 '1154',
 '1188',
 '1193',
 '1218',
 '1222',
 '1224',
 '1226',
 '1228',
 '1235',
 '1237',
 '1249',
 '1260',
 '1262',
 '1264',
 '1428',
 '7896',
 '7899',
 '1142',
 '1240',
 '2600',
 '30',
 '2092',
 '2093',
 '3624',
 '9643',
 '9461',
 '9510',
 '9540',
 '1104A',
 '706',
 '1088',
 '1091',
 '1099',
 '1134',
 '1169',
 '1170',
 '1195',
 '1199',
 '1243',
 '1251',
 '1257',
 '1277',
 '1279',
 '1233',
 '54',
 '1600',
 '2287',
 '4118',
 '9289',
 '85',
 '555',
 '620',
 '630',
 '1149',
 '1503',
 '1531',
 '232',
 265,
 267,
 269,
 271,
 273,
 275,
 277,
 279,
 281,
 283,
 285,
 287,
 289,
 291,
 293,
 295,
 297,
 300,
 302,
 304,
 306,
 308,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 334,
 336,
 340,
 342,
 344,
 346,
 348,
 350,
 352,
 366,
 380,
 382,
 384,
 386,
 388,
 390,
 404,
 406,
 410,
 414,
 430,
 432,
 434,
 439,
 443,
 445,
 448,
 449,
 455,
 461,
 481,
 486,
 492,
 500,
 502,
 510,
 530,
 532,
 536,
 546,
 572,
 574,
 576,
 582,
 592,
 600,
 602,
 622,
 632,
 638,
 642,
 702,
 704,
 706,
 708,
 750,
 752,
 755,
 757,
 763,
 801,
 805,
 833,
 841,
 843,
 864,
 888,
 890,
 892,
 895,
 897,
 1088,
 1091,
 1117,
 1126,
 1128,
 1134,
 1136,
 1141,
 1146,
 1166,
 1170,
 1176,
 1178,
 1186,
 1188,
 1191,
 1193,
 1197,
 1199,
 1222,
 1224,
 1226,
 1241,
 1243,
 1246,
 1247,
 1259,
 1267,
 1269,
 1277,
 1279,
 1281,
 1446,
 2370,
 2372,
 2374,
 2474,
 7811,
 7813,
 7896,
 7899,
 7911,
 1101,
 1102,
 1106,
 1230,
 1235,
 1236,
 1237,
 1238,
 1239,
 1261,
 33,
 43,
 50,
 54,
 200,
 202,
 402,
 700,
 1031,
 1033,
 4,
 6,
 8,
 10,
 26,
 32,
 52,
 86,
 88,
 110,
 112,
 201,
 203,
 207,
 251,
 253,
 255,
 301,
 305,
 307,
 400]

In [66]:
print(pd.Series(list( "".join(df["Vlo-I"].astype(str).unique().tolist() ))).value_counts())

1    368
2    251
0    203
3    190
4    175
6    161
9    154
5    151
8    148
7    120
P      3
A      2
dtype: int64

"Vlo-I" tiene problemas con letras mezcladas con los dígitos

In [67]:
import re
df["Vlo-I"].astype(str).apply(lambda x: re.findall(r'\d+', x)[0] ).unique().tolist()

['226',
 '912',
 '940',
 '92',
 '93',
 '401',
 '11',
 '1011',
 '1281',
 '1283',
 '1285',
 '1287',
 '1289',
 '1291',
 '2291',
 '98',
 '116',
 '176',
 '240',
 '295',
 '689',
 '250',
 '112',
 '118',
 '174',
 '249',
 '276',
 '495',
 '4495',
 '146',
 '7661',
 '7663',
 '9245',
 '9268',
 '9362',
 '6830',
 '702',
 '624',
 '28',
 '846',
 '709',
 '741',
 '8021',
 '8023',
 '8027',
 '8029',
 '8069',
 '8073',
 '8075',
 '8099',
 '8125',
 '8137',
 '8160',
 '8161',
 '9601',
 '9615',
 '9651',
 '9653',
 '9661',
 '9689',
 '9782',
 '9623',
 '1',
 '3',
 '7',
 '9',
 '13',
 '15',
 '17',
 '21',
 '23',
 '25',
 '41',
 '43',
 '51',
 '53',
 '55',
 '61',
 '71',
 '73',
 '75',
 '81',
 '83',
 '102',
 '104',
 '106',
 '108',
 '110',
 '120',
 '122',
 '128',
 '130',
 '132',
 '134',
 '140',
 '142',
 '150',
 '156',
 '160',
 '162',
 '164',
 '166',
 '170',
 '172',
 '180',
 '182',
 '184',
 '186',
 '188',
 '190',
 '192',
 '194',
 '196',
 '501',
 '503',
 '507',
 '521',
 '531',
 '551',
 '800',
 '802',
 '804',
 '1083',
 '14',
 '31',
 '35',
 '37',
 '57',
 '65',
 '67',
 '69',
 '89',
 '91',
 '97',
 '114',
 '124',
 '126',
 '136',
 '138',
 '144',
 '148',
 '152',
 '154',
 '168',
 '178',
 '201',
 '203',
 '207',
 '209',
 '211',
 '213',
 '215',
 '217',
 '219',
 '221',
 '231',
 '233',
 '235',
 '237',
 '239',
 '241',
 '247',
 '251',
 '257',
 '259',
 '261',
 '263',
 '265',
 '267',
 '269',
 '271',
 '273',
 '275',
 '277',
 '279',
 '281',
 '283',
 '285',
 '287',
 '289',
 '291',
 '293',
 '297',
 '300',
 '302',
 '304',
 '306',
 '308',
 '312',
 '314',
 '318',
 '320',
 '322',
 '324',
 '326',
 '328',
 '330',
 '332',
 '334',
 '336',
 '338',
 '340',
 '342',
 '344',
 '346',
 '348',
 '350',
 '366',
 '374',
 '380',
 '382',
 '384',
 '386',
 '388',
 '396',
 '403',
 '405',
 '439',
 '443',
 '445',
 '449',
 '451',
 '455',
 '461',
 '481',
 '500',
 '502',
 '504',
 '510',
 '530',
 '532',
 '534',
 '546',
 '572',
 '574',
 '576',
 '582',
 '592',
 '600',
 '602',
 '622',
 '632',
 '642',
 '646',
 '648',
 '650',
 '704',
 '708',
 '750',
 '752',
 '760',
 '772',
 '776',
 '778',
 '798',
 '801',
 '833',
 '841',
 '843',
 '845',
 '849',
 '900',
 '902',
 '906',
 '910',
 '930',
 '932',
 '934',
 '942',
 '952',
 '954',
 '968',
 '970',
 '972',
 '986',
 '988',
 '991',
 '993',
 '1320',
 '1322',
 '1326',
 '1334',
 '1357',
 '1359',
 '1446',
 '1498',
 '2632',
 '2636',
 '2638',
 '2640',
 '2650',
 '2702',
 '4501',
 '4503',
 '1003',
 '1004',
 '1005',
 '1302',
 '1340',
 '200',
 '700',
 '1704',
 '33',
 '59',
 '95',
 '243',
 '634',
 '1200',
 '1202',
 '1300',
 '1071',
 '99',
 '158',
 '198',
 '205',
 '376',
 '378',
 '404',
 '406',
 '410',
 '414',
 '430',
 '432',
 '434',
 '438',
 '486',
 '492',
 '536',
 '638',
 '640',
 '644',
 '864',
 '890',
 '892',
 '1122',
 '1126',
 '1151',
 '1363',
 '1946',
 '2370',
 '2372',
 '2374',
 '7811',
 '7813',
 '1165',
 '1301',
 '1351',
 '1906',
 '204',
 '9625',
 '8665',
 '4950',
 '45',
 '100',
 '523',
 '1025',
 '4000',
 '63',
 '352',
 '354',
 '452',
 '460',
 '636',
 '674',
 '888',
 '895',
 '897',
 '1108',
 '1124',
 '1128',
 '1236',
 '1248',
 '2364',
 '2366',
 '2378',
 '2474',
 '2478',
 '1050',
 '1051',
 '1052',
 '1061',
 '1101',
 '1102',
 '1104',
 '1130',
 '1159',
 '1230',
 '202',
 '989',
 '3000',
 '9000',
 '459',
 '483',
 '1114',
 '1168',
 '1238',
 '1239',
 '1261',
 '1107',
 '1140',
 '1167',
 '1271',
 '1031',
 '1700',
 '9659',
 '1551',
 '1800',
 '358',
 '1103',
 '1111',
 '2518',
 '7959',
 '400',
 '402',
 '2297',
 '9244',
 '9246',
 '9247',
 '9261',
 '9272',
 '9673',
 '9956',
 '9600',
 '9629',
 '9662',
 '9701',
 '9955',
 '5',
 '77',
 '553',
 '316',
 '368',
 '372',
 '470',
 '506',
 '604',
 '1136',
 '1158',
 '1242',
 '1244',
 '2368',
 '2486',
 '1105',
 '1106',
 '1113',
 '1115',
 '1132',
 '1155',
 '1166',
 '2488',
 '1400',
 '1033',
 '4',
 '8',
 '26',
 '22',
 '1927',
 '7721',
 '591',
 '8519',
 '8525',
 '8541',
 '8542',
 '9622',
 '356',
 '1138',
 '1148',
 '1041',
 '6',
 '32',
 '50',
 '52',
 '86',
 '88',
 '9301',
 '9303',
 '47',
 '60',
 '1234',
 '1250',
 '1241',
 '1034',
 '1035',
 '1043',
 '7704',
 '10',
 '253',
 '1502',
 '8083',
 '8131',
 '9851',
 '27',
 '543',
 '1198',
 '39',
 '87',
 '390',
 '448',
 '664',
 '805',
 '1054',
 '1065',
 '1116',
 '1121',
 '1146',
 '1154',
 '1188',
 '1193',
 '1218',
 '1222',
 '1224',
 '1226',
 '1228',
 '1235',
 '1237',
 '1249',
 '1260',
 '1262',
 '1264',
 '1428',
 '7896',
 '7899',
 '1142',
 '1240',
 '2600',
 '30',
 '2092',
 '2093',
 '3624',
 '9643',
 '9461',
 '9510',
 '9540',
 '706',
 '1088',
 '1091',
 '1099',
 '1134',
 '1169',
 '1170',
 '1195',
 '1199',
 '1243',
 '1251',
 '1257',
 '1277',
 '1279',
 '1233',
 '54',
 '1600',
 '2287',
 '4118',
 '9289',
 '85',
 '555',
 '620',
 '630',
 '1149',
 '1503',
 '1531',
 '232',
 '755',
 '757',
 '763',
 '1117',
 '1141',
 '1176',
 '1178',
 '1186',
 '1191',
 '1197',
 '1246',
 '1247',
 '1259',
 '1267',
 '1269',
 '7911',
 '255',
 '301',
 '305',
 '307']

In [68]:
df["Vlo-I"] = df["Vlo-I"].astype(str).apply(lambda x: re.findall(r'\d+', x)[0] ).astype(int)
df["Vlo-I"].unique()

array([ 226,  912,  940,   92,   93,  401,   11, 1011, 1281, 1283, 1285,
       1287, 1289, 1291, 2291,   98,  116,  176,  240,  295,  689,  250,
        112,  118,  174,  249,  276,  495, 4495,  146, 7661, 7663, 9245,
       9268, 9362, 6830,  702,  624,   28,  846,  709,  741, 8021, 8023,
       8027, 8029, 8069, 8073, 8075, 8099, 8125, 8137, 8160, 8161, 9601,
       9615, 9651, 9653, 9661, 9689, 9782, 9623,    1,    3,    7,    9,
         13,   15,   17,   21,   23,   25,   41,   43,   51,   53,   55,
         61,   71,   73,   75,   81,   83,  102,  104,  106,  108,  110,
        120,  122,  128,  130,  132,  134,  140,  142,  150,  156,  160,
        162,  164,  166,  170,  172,  180,  182,  184,  186,  188,  190,
        192,  194,  196,  501,  503,  507,  521,  531,  551,  800,  802,
        804, 1083,   14,   31,   35,   37,   57,   65,   67,   69,   89,
         91,   97,  114,  124,  126,  136,  138,  144,  148,  152,  154,
        168,  178,  201,  203,  207,  209,  211,  213,  215,  217,  219,
        221,  231,  233,  235,  237,  239,  241,  247,  251,  257,  259,
        261,  263,  265,  267,  269,  271,  273,  275,  277,  279,  281,
        283,  285,  287,  289,  291,  293,  297,  300,  302,  304,  306,
        308,  312,  314,  318,  320,  322,  324,  326,  328,  330,  332,
        334,  336,  338,  340,  342,  344,  346,  348,  350,  366,  374,
        380,  382,  384,  386,  388,  396,  403,  405,  439,  443,  445,
        449,  451,  455,  461,  481,  500,  502,  504,  510,  530,  532,
        534,  546,  572,  574,  576,  582,  592,  600,  602,  622,  632,
        642,  646,  648,  650,  704,  708,  750,  752,  760,  772,  776,
        778,  798,  801,  833,  841,  843,  845,  849,  900,  902,  906,
        910,  930,  932,  934,  942,  952,  954,  968,  970,  972,  986,
        988,  991,  993, 1320, 1322, 1326, 1334, 1357, 1359, 1446, 1498,
       2632, 2636, 2638, 2640, 2650, 2702, 4501, 4503, 1003, 1004, 1005,
       1302, 1340,  200,  700, 1704,   33,   59,   95,  243,  634, 1200,
       1202, 1300, 1071,   99,  158,  198,  205,  376,  378,  404,  406,
        410,  414,  430,  432,  434,  438,  486,  492,  536,  638,  640,
        644,  864,  890,  892, 1122, 1126, 1151, 1363, 1946, 2370, 2372,
       2374, 7811, 7813, 1165, 1301, 1351, 1906,  204, 9625, 8665, 4950,
         45,  100,  523, 1025, 4000,   63,  352,  354,  452,  460,  636,
        674,  888,  895,  897, 1108, 1124, 1128, 1236, 1248, 2364, 2366,
       2378, 2474, 2478, 1050, 1051, 1052, 1061, 1101, 1102, 1104, 1130,
       1159, 1230,  202,  989, 3000, 9000,  459,  483, 1114, 1168, 1238,
       1239, 1261, 1107, 1140, 1167, 1271, 1031, 1700, 9659, 1551, 1800,
        358, 1103, 1111, 2518, 7959,  400,  402, 2297, 9244, 9246, 9247,
       9261, 9272, 9673, 9956, 9600, 9629, 9662, 9701, 9955,    5,   77,
        553,  316,  368,  372,  470,  506,  604, 1136, 1158, 1242, 1244,
       2368, 2486, 1105, 1106, 1113, 1115, 1132, 1155, 1166, 2488, 1400,
       1033,    4,    8,   26,   22, 1927, 7721,  591, 8519, 8525, 8541,
       8542, 9622,  356, 1138, 1148, 1041,    6,   32,   50,   52,   86,
         88, 9301, 9303,   47,   60, 1234, 1250, 1241, 1034, 1035, 1043,
       7704,   10,  253, 1502, 8083, 8131, 9851,   27,  543, 1198,   39,
         87,  390,  448,  664,  805, 1054, 1065, 1116, 1121, 1146, 1154,
       1188, 1193, 1218, 1222, 1224, 1226, 1228, 1235, 1237, 1249, 1260,
       1262, 1264, 1428, 7896, 7899, 1142, 1240, 2600,   30, 2092, 2093,
       3624, 9643, 9461, 9510, 9540,  706, 1088, 1091, 1099, 1134, 1169,
       1170, 1195, 1199, 1243, 1251, 1257, 1277, 1279, 1233,   54, 1600,
       2287, 4118, 9289,   85,  555,  620,  630, 1149, 1503, 1531,  232,
        755,  757,  763, 1117, 1141, 1176, 1178, 1186, 1191, 1197, 1246,
       1247, 1259, 1267, 1269, 7911,  255,  301,  305,  307])

In [69]:
print(pd.Series(list( "".join(df["Vlo-I"].astype(str).unique().tolist() ))).value_counts())

1    366
2    251
0    201
3    190
4    172
6    160
9    153
5    151
8    147
7    120
dtype: int64

In [70]:
len(list(df["Vlo-O"].unique()))

867

In [71]:
list(df["Vlo-O"].unique())

['226',
 '912',
 '940',
 '92',
 '93',
 '401',
 '11',
 '1011',
 '1281',
 '1283',
 '1285',
 '1287',
 '1289',
 '1291',
 '2291',
 '98',
 '116',
 '176',
 '240',
 '295',
 '689',
 '250',
 '112',
 '118',
 '174',
 '249',
 '276',
 '495',
 '4495',
 '146',
 '7661',
 '7663',
 '9245',
 '9268',
 '9362',
 '6830',
 '702',
 '624',
 '28',
 '846',
 '709',
 '741',
 '8021',
 '8023',
 '8027',
 '8029',
 '8069',
 '8073',
 '8075',
 '8099',
 '8125',
 '8137',
 '8160',
 '8161',
 '9601',
 '9615',
 '9651',
 '9653',
 '9661',
 '9689',
 '9782',
 '9623',
 '1',
 '3',
 '7',
 '9',
 '13',
 '15',
 '17',
 '21',
 '23',
 '25',
 '41',
 '43',
 '51',
 '53',
 '55',
 '61',
 '71',
 '73',
 '75',
 '81',
 '83',
 '102',
 '104',
 '106',
 '108',
 '110',
 '120',
 '122',
 '128',
 '130',
 '132',
 '134',
 '140',
 '142',
 '150',
 '156',
 '160',
 '162',
 '164',
 '166',
 '170',
 '172',
 '180',
 '182',
 '184',
 '186',
 '188',
 '190',
 '192',
 '194',
 '196',
 '501',
 '503',
 '507',
 '521',
 '531',
 '551',
 '800',
 '802',
 '804',
 '1083',
 '14',
 '31',
 '35',
 '37',
 '57',
 '65',
 '67',
 '69',
 '89',
 '91',
 '97',
 '114',
 '124',
 '126',
 '136',
 '138',
 '144',
 '148',
 '152',
 '154',
 '168',
 '178',
 '201',
 '203',
 '207',
 '209',
 '211',
 '213',
 '215',
 '217',
 '219',
 '221',
 '231',
 '233',
 '235',
 '237',
 '239',
 '241',
 '247',
 '251',
 '257',
 '259',
 '261',
 '263',
 '265',
 '267',
 '269',
 '271',
 '273',
 '275',
 '277',
 '279',
 '281',
 '283',
 '285',
 '287',
 '289',
 '291',
 '293',
 '297',
 '300',
 '302',
 '304',
 '306',
 '308',
 '312',
 '314',
 '318',
 '320',
 '322',
 '324',
 '326',
 '328',
 '330',
 '332',
 '334',
 '336',
 '338',
 '340',
 '342',
 '344',
 '346',
 '348',
 '350',
 '366',
 '374',
 '380',
 '382',
 '384',
 '386',
 '388',
 '396',
 '403',
 '405',
 '439',
 '443',
 '445',
 '449',
 '451',
 '455',
 '461',
 '481',
 '500',
 '502',
 '504',
 '510',
 '530',
 '532',
 '534',
 '546',
 '572',
 '574',
 '576',
 '582',
 '592',
 '600',
 '602',
 '622',
 '632',
 '642',
 '646',
 '648',
 '650',
 '704',
 '708',
 '750',
 '752',
 '760',
 '772',
 '776',
 '778',
 '798',
 '801',
 '833',
 '841',
 '843',
 '845',
 '849',
 '900',
 '902',
 '906',
 '910',
 '930',
 '932',
 '934',
 '942',
 '952',
 '954',
 '968',
 '970',
 '972',
 '986',
 '988',
 '991',
 '993',
 '1320',
 '1322',
 '1326',
 '1334',
 '1357',
 '1359',
 '1446',
 '1498',
 '2632',
 '2636',
 '2638',
 '2640',
 '2650',
 '2702',
 '4501',
 '1001',
 '1003',
 '4503',
 '1004',
 '1005',
 '1302',
 '1340',
 '200',
 nan,
 '700',
 '1700',
 '33',
 '59',
 '95',
 '243',
 '1318',
 '634',
 '1304',
 '1303',
 '1200',
 '1202',
 '1300',
 '71R',
 '99',
 '158',
 '198',
 '205',
 '1101',
 '376',
 '378',
 '404',
 '406',
 '410',
 '414',
 '430',
 '432',
 '434',
 '438',
 '486',
 '492',
 '1346',
 '536',
 '638',
 '640',
 '644',
 '864',
 '890',
 '892',
 '1122',
 '1126',
 '1151',
 '1363',
 '1361',
 '1946',
 '2370',
 '2372',
 '2374',
 '7811',
 '1103',
 '1061',
 '7813',
 '1071',
 '201R',
 '1165',
 '1301',
 '1351',
 '1906',
 '202',
 '1704',
 '9625',
 '8665',
 '4950',
 '45',
 '100',
 '523',
 '1025',
 '4000',
 '63',
 '352',
 '354',
 '452',
 '460',
 '636',
 '674',
 '888',
 '895',
 '897',
 '1108',
 '1124',
 '1128',
 '1236',
 '1248',
 '2364',
 '2366',
 '2378',
 '2474',
 '2478',
 '1050',
 '1051',
 '1052',
 '1102',
 '1104',
 '1130',
 '1159',
 '1230',
 '43R',
 '989',
 '2093',
 '401A',
 '401B',
 '3000',
 '9000',
 '802R',
 '459',
 '483',
 '1160',
 '1114',
 '1168',
 '1238',
 '1239',
 '1261',
 '114R',
 '622R',
 '1107',
 '1140',
 '1167',
 '1271',
 '1031',
 '9659',
 '1551',
 '1800',
 '358',
 '492R',
 '1111',
 '2518',
 '7959',
 '1041',
 '400',
 '402',
 '2297',
 '1297',
 '4118',
 '9858',
 '9860',
 '9244',
 '9246',
 '9247',
 '9261',
 '9272',
 '2726',
 '9673',
 '9956',
 '9600',
 '9629',
 '9662',
 '9701',
 '9955',
 '5',
 '77',
 '553',
 '316',
 '368',
 '372',
 '1155',
 '470',
 '506',
 '604',
 '2486',
 '1136',
 '1158',
 '1242',
 '1244',
 '2368',
 '1113',
 '338R',
 '1105',
 '1106',
 '1115',
 '1132',
 '1166',
 '2488',
 '1400',
 '1033',
 '4',
 '8',
 '26',
 '22',
 '1927',
 '7721',
 '922',
 '5924',
 '591P',
 '2763',
 '2804',
 '8519',
 '8525',
 '8541',
 '8542',
 '9622',
 '356',
 '1138',
 '1148',
 '6',
 '32',
 '50',
 '52',
 '86',
 '88',
 '9301',
 '9303',
 '846A',
 '47',
 '60',
 '1234',
 '1250',
 '1241',
 '1034',
 '1035',
 '1043',
 '7704',
 '10',
 '253',
 '1502',
 '8083',
 '8131',
 '9851',
 '27',
 '543',
 '1198',
 '39',
 '87',
 '390',
 '448',
 '664',
 '805',
 '1054',
 '1065',
 '1116',
 '1121',
 '1146',
 '1154',
 '1188',
 '1193',
 '1218',
 '1222',
 '1224',
 '1226',
 '1228',
 '1235',
 '1237',
 '1249',
 '1260',
 '1262',
 '1264',
 '1428',
 '7896',
 '7899',
 '502R',
 '1142',
 '1240',
 '2600',
 '30',
 '2092',
 '3624',
 '9643',
 '9461',
 '9510',
 '9540',
 '706',
 '1088',
 '1091',
 '1099',
 '1134',
 '1169',
 '1170',
 '1195',
 '1199',
 '1243',
 '1251',
 '1257',
 '1277',
 '1279',
 '207R',
 '1233',
 '54',
 '1600',
 '2287',
 '9289',
 '85',
 '150.0',
 '156.0',
 '160.0',
 '162.0',
 '164.0',
 '166.0',
 '168.0',
 '170.0',
 '172.0',
 '174.0',
 '176.0',
 '180.0',
 '182.0',
 '184.0',
 '186.0',
 '190.0',
 '192.0',
 '194.0',
 '196.0',
 '198.0',
 '501.0',
 '503.0',
 '507.0',
 '521.0',
 '531.0',
 '543.0',
 '551.0',
 '553.0',
 '555.0',
 '620.0',
 '630.0',
 '800.0',
 '802.0',
 '804.0',
 '1149.0',
 '1503.0',
 '1531.0',
 '1.0',
 '9.0',
 '14.0',
 '31.0',
 '35.0',
 '37.0',
 '39.0',
 '53.0',
 '57.0',
 '59.0',
 '61.0',
 '63.0',
 '65.0',
 '69.0',
 '87.0',
 '91.0',
 '93.0',
 '95.0',
 '97.0',
 '99.0',
 '114.0',
 '120.0',
 '122.0',
 '124.0',
 '126.0',
 '128.0',
 '130.0',
 '134.0',
 '136.0',
 '138.0',
 '140.0',
 '142.0',
 '144.0',
 '146.0',
 '148.0',
 '152.0',
 '154.0',
 '158.0',
 '188.0',
 '201.0',
 '203.0',
 '205.0',
 '207.0',
 '209.0',
 '211.0',
 '213.0',
 '215.0',
 '217.0',
 '219.0',
 '221.0',
 '231.0',
 '232.0',
 '235.0',
 '237.0',
 '239.0',
 '241.0',
 '251.0',
 '257.0',
 '259.0',
 '261.0',
 '263.0',
 '265.0',
 265.0,
 267.0,
 269.0,
 271.0,
 273.0,
 275.0,
 277.0,
 279.0,
 281.0,
 283.0,
 285.0,
 287.0,
 289.0,
 291.0,
 293.0,
 295.0,
 297.0,
 300.0,
 302.0,
 304.0,
 306.0,
 308.0,
 312.0,
 314.0,
 316.0,
 318.0,
 320.0,
 322.0,
 324.0,
 326.0,
 328.0,
 330.0,
 334.0,
 336.0,
 340.0,
 342.0,
 344.0,
 346.0,
 348.0,
 350.0,
 352.0,
 366.0,
 380.0,
 382.0,
 384.0,
 386.0,
 388.0,
 390.0,
 404.0,
 406.0,
 410.0,
 414.0,
 430.0,
 432.0,
 434.0,
 439.0,
 443.0,
 445.0,
 448.0,
 449.0,
 455.0,
 461.0,
 481.0,
 486.0,
 492.0,
 500.0,
 502.0,
 510.0,
 530.0,
 532.0,
 536.0,
 546.0,
 572.0,
 574.0,
 576.0,
 582.0,
 592.0,
 600.0,
 602.0,
 622.0,
 632.0,
 638.0,
 642.0,
 702.0,
 704.0,
 706.0,
 708.0,
 750.0,
 752.0,
 755.0,
 757.0,
 763.0,
 801.0,
 805.0,
 833.0,
 841.0,
 843.0,
 864.0,
 888.0,
 890.0,
 892.0,
 895.0,
 897.0,
 1088.0,
 1091.0,
 1117.0,
 1126.0,
 1128.0,
 1134.0,
 1136.0,
 1141.0,
 1146.0,
 1166.0,
 1170.0,
 1176.0,
 1178.0,
 1186.0,
 1188.0,
 1191.0,
 1193.0,
 1197.0,
 1199.0,
 1222.0,
 1224.0,
 1226.0,
 1241.0,
 1243.0,
 1246.0,
 1247.0,
 1259.0,
 1267.0,
 1269.0,
 1277.0,
 1279.0,
 1281.0,
 1446.0,
 2370.0,
 2372.0,
 2374.0,
 2474.0,
 7811.0,
 7813.0,
 7896.0,
 7899.0,
 7911.0,
 1101.0,
 1102.0,
 1106.0,
 1230.0,
 1235.0,
 1236.0,
 1237.0,
 1238.0,
 1239.0,
 1261.0,
 33.0,
 43.0,
 50.0,
 54.0,
 200.0,
 202.0,
 402.0,
 700.0,
 1031.0,
 1033.0,
 4.0,
 6.0,
 8.0,
 10.0,
 26.0,
 32.0,
 52.0,
 86.0,
 88.0,
 110.0,
 112.0,
 201.0,
 203.0,
 207.0,
 251.0,
 253.0,
 255.0,
 301.0,
 305.0,
 307.0,
 400.0]

In [72]:
print(pd.Series(list( "".join(df["Vlo-O"].astype(str).unique().tolist() ))).value_counts())

0    566
1    519
2    380
3    294
.    280
4    256
6    226
8    220
5    211
9    203
7    171
R     10
A      2
n      2
a      1
B      1
P      1
dtype: int64

In [73]:
characters = pd.Series(list( "".join(df["Vlo-O"].astype(str).unique().tolist() ))).value_counts().index.tolist()
my_characters = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '.']
for x in my_characters:
    characters.remove(x)
print(characters)

['R', 'A', 'n', 'a', 'B', 'P']

In [55]:
"nan".replace("n", "").replace("a", "")

''

In [81]:
x = "81"
x.replace("8", "")
print(x)

81

In [83]:
def clean_Vlo_O(x):
    x = str(x)
    for c in characters:
        x = x.replace(c, "")
    if x == "":
        return -999
    return int(float(x))

df["Vlo-O"].apply(lambda x: clean_Vlo_O(x) ).unique()#.astype(int)

array([ 226,  912,  940,   92,   93,  401,   11, 1011, 1281, 1283, 1285,
       1287, 1289, 1291, 2291,   98,  116,  176,  240,  295,  689,  250,
        112,  118,  174,  249,  276,  495, 4495,  146, 7661, 7663, 9245,
       9268, 9362, 6830,  702,  624,   28,  846,  709,  741, 8021, 8023,
       8027, 8029, 8069, 8073, 8075, 8099, 8125, 8137, 8160, 8161, 9601,
       9615, 9651, 9653, 9661, 9689, 9782, 9623,    1,    3,    7,    9,
         13,   15,   17,   21,   23,   25,   41,   43,   51,   53,   55,
         61,   71,   73,   75,   81,   83,  102,  104,  106,  108,  110,
        120,  122,  128,  130,  132,  134,  140,  142,  150,  156,  160,
        162,  164,  166,  170,  172,  180,  182,  184,  186,  188,  190,
        192,  194,  196,  501,  503,  507,  521,  531,  551,  800,  802,
        804, 1083,   14,   31,   35,   37,   57,   65,   67,   69,   89,
         91,   97,  114,  124,  126,  136,  138,  144,  148,  152,  154,
        168,  178,  201,  203,  207,  209,  211,  213,  215,  217,  219,
        221,  231,  233,  235,  237,  239,  241,  247,  251,  257,  259,
        261,  263,  265,  267,  269,  271,  273,  275,  277,  279,  281,
        283,  285,  287,  289,  291,  293,  297,  300,  302,  304,  306,
        308,  312,  314,  318,  320,  322,  324,  326,  328,  330,  332,
        334,  336,  338,  340,  342,  344,  346,  348,  350,  366,  374,
        380,  382,  384,  386,  388,  396,  403,  405,  439,  443,  445,
        449,  451,  455,  461,  481,  500,  502,  504,  510,  530,  532,
        534,  546,  572,  574,  576,  582,  592,  600,  602,  622,  632,
        642,  646,  648,  650,  704,  708,  750,  752,  760,  772,  776,
        778,  798,  801,  833,  841,  843,  845,  849,  900,  902,  906,
        910,  930,  932,  934,  942,  952,  954,  968,  970,  972,  986,
        988,  991,  993, 1320, 1322, 1326, 1334, 1357, 1359, 1446, 1498,
       2632, 2636, 2638, 2640, 2650, 2702, 4501, 1001, 1003, 4503, 1004,
       1005, 1302, 1340,  200, -999,  700, 1700,   33,   59,   95,  243,
       1318,  634, 1304, 1303, 1200, 1202, 1300,   99,  158,  198,  205,
       1101,  376,  378,  404,  406,  410,  414,  430,  432,  434,  438,
        486,  492, 1346,  536,  638,  640,  644,  864,  890,  892, 1122,
       1126, 1151, 1363, 1361, 1946, 2370, 2372, 2374, 7811, 1103, 1061,
       7813, 1071, 1165, 1301, 1351, 1906,  202, 1704, 9625, 8665, 4950,
         45,  100,  523, 1025, 4000,   63,  352,  354,  452,  460,  636,
        674,  888,  895,  897, 1108, 1124, 1128, 1236, 1248, 2364, 2366,
       2378, 2474, 2478, 1050, 1051, 1052, 1102, 1104, 1130, 1159, 1230,
        989, 2093, 3000, 9000,  459,  483, 1160, 1114, 1168, 1238, 1239,
       1261, 1107, 1140, 1167, 1271, 1031, 9659, 1551, 1800,  358, 1111,
       2518, 7959, 1041,  400,  402, 2297, 1297, 4118, 9858, 9860, 9244,
       9246, 9247, 9261, 9272, 2726, 9673, 9956, 9600, 9629, 9662, 9701,
       9955,    5,   77,  553,  316,  368,  372, 1155,  470,  506,  604,
       2486, 1136, 1158, 1242, 1244, 2368, 1113, 1105, 1106, 1115, 1132,
       1166, 2488, 1400, 1033,    4,    8,   26,   22, 1927, 7721,  922,
       5924,  591, 2763, 2804, 8519, 8525, 8541, 8542, 9622,  356, 1138,
       1148,    6,   32,   50,   52,   86,   88, 9301, 9303,   47,   60,
       1234, 1250, 1241, 1034, 1035, 1043, 7704,   10,  253, 1502, 8083,
       8131, 9851,   27,  543, 1198,   39,   87,  390,  448,  664,  805,
       1054, 1065, 1116, 1121, 1146, 1154, 1188, 1193, 1218, 1222, 1224,
       1226, 1228, 1235, 1237, 1249, 1260, 1262, 1264, 1428, 7896, 7899,
       1142, 1240, 2600,   30, 2092, 3624, 9643, 9461, 9510, 9540,  706,
       1088, 1091, 1099, 1134, 1169, 1170, 1195, 1199, 1243, 1251, 1257,
       1277, 1279, 1233,   54, 1600, 2287, 9289,   85,  555,  620,  630,
       1149, 1503, 1531,  232,  755,  757,  763, 1117, 1141, 1176, 1178,
       1186, 1191, 1197, 1246, 1247, 1259, 1267, 1269, 7911,  255,  301,
        305,  307], dtype=int64)

In [85]:
df["Vlo-O"] = df["Vlo-O"].apply(lambda x: clean_Vlo_O(x) )

In [86]:
df [df["Vlo-O"]== -999]

,Fecha-I,Vlo-I,Ori-I,Des-I,Emp-I,Fecha-O,Vlo-O,Ori-O,Des-O,Emp-O,DIA,MES,AÑO,DIANOM,TIPOVUELO,OPERA,SIGLAORI,SIGLADES
6068,2017-01-19 11:00:00,200,SCEL,SPJC,LAW,2017-01-19 11:03:00,-999,SCEL,SPJC,56R,19,1,2017,Jueves,I,Latin American Wings,Santiago,Lima

In [87]:
profile_name = "Fligths data report v2"
profile = ProfileReport(df, title=profile_name )
profile.to_file(output_file='{}.html'.format(profile_name ))

Summarize dataset: 100%|██████████| 47/47 [00:12<00:00,  3.76it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:04<00:00,  4.88s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.11s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 142.46it/s]